### PR TITLE
sync with agrc python template

### PR DESCRIPTION
**Pull request by steveoh**
https://github.com/agrc/python

### CODE REVIEW

**Comment by stdavis** [comment]
Assuming that everything runs I think that this LGTM. Is `pylint_quotes` specified anywhere as a dev dependency? I'm guessing the created a bunch of linting warnings and errors?

**Comment by steveoh** [comment]
> Is `pylint_quotes` specified anywhere as a dev dependency? 

What makes more sense, a `requirements.txt` or a `setup.py`? Probably a `requirements.txt` in my opinion.

I'll add one if you agree

**Comment by stdavis** [comment]
Yes, I agree, `requirements.txt` since this isn't an installable project.

**Comment by steveoh** [comment]
@jacobdadams and @stdavis how does this look?

**Review by stdavis — APPROVED** [review]

**Comment by jacobdadams** [comment]
Looks good to me. I haven't had a chance to wrap my head around agrc/python, but I don't see any issues with the changes here.

**Review by jacobdadams — APPROVED** [review]

**Pull request merged**
